# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"
ignore_deps = ["github.com/coredns/coredns"]

# previous release
previous = "v1.8.0"

pre_release = true

preface = """
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description = """\
Linux: 6.6.58
containerd: 2.0.0-rc.6
Flannel: 0.26.0
Kubernetes: 1.32.0-alpha.2
runc: 1.2.0

Talos is built with Go 1.23.2.
"""

    [notes.cgroups]
        title = "`talosctl cgroups`"
        description = """\
The `talosctl cgroups` command has been added to the `talosctl` tool.
This command allows you to view the cgroup resource consumption and limits for a machine, e.g.
`talosctl cgroups --preset memory`.
"""

    [notes.udevd]
        title = "udevd"
        description = """\
Talos previously used `udevd` to provide `udevd`, now it uses `systemd-udevd` instead.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
